### ISSUE TITLE
IsNotNil and other checks not working

### ISSUE THREAD

**Issue by ranjithchev** [ahmetcanozcan/fet#1]
Hi

If I have something like this
var mySliceIntf interface{}
var myInt int
mySliceIntf = myInt

fet.Field("col").In(myInt, fet.IfNotNil) does not eliminate "col" because IfNotNil takes in value as interface{} type and hence the comparison value != nil does not work. Please let me know.

Thanks

**Comment by ahmetcanozcan** [comment]
Hi, 

You are using the `IfNotNil` checker for an int value so  `myInt` value is `0` in here. So `col` field would exist in the filter. You can use `IfNotZero` checker for  `int` values as well.
